# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=6.14.4'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-6.14.4'
  - '.'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.12.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.12.0'
  # 8.12.0 is tagged :latest
  - '--tag=gcr.io/$PROJECT_ID/npm:latest'
  - '.'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.4.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.4.0'
  - '.'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=9.11.2'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-9.11.2'
  - '.'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=10.10.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-10.10.0'
  # 10.10.0 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/npm:current'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/npm:node-6.14.4'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-8.12.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-9.11.2'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-10.10.0'
  args: ['version']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install','-g','@angular/cli@1.7.4' ]

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run','ng','build']
  
- name: "gcr.io/cloud-builders/gcloud"
  args: ["config", "set", "project", 'nguiapp-gcp']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]

images:
- 'gcr.io/$PROJECT_ID/npm:latest'
- 'gcr.io/$PROJECT_ID/npm:current'
- 'gcr.io/$PROJECT_ID/npm:node-6.14.4'
- 'gcr.io/$PROJECT_ID/npm:node-8.12.0'
- 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
- 'gcr.io/$PROJECT_ID/npm:node-9.11.2'
- 'gcr.io/$PROJECT_ID/npm:node-10.10.0'
