steps:

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'i' ]

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build', '--prod', '--build-optimizer' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '-v=1']