steps:
# Install Angular
- name: 'gcr.io/cloud-builders/npm'
  args: ['install','-g','@angular/cli@6.0.7' ]
# Install Dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# build Project in mode Prod.
- name: 'gcr.io/cloud-builders/npm'
  args: ['run','ng','build']

# Select the project for the app to be deployed
- name: "gcr.io/cloud-builders/gcloud"
  args: ["config", "set", "project", "nguiapp-gcp"]
# deploy in App Engine
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "2000s" 
