# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=10.10.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-10.10.0'
  # 10.10.0 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/npm:current'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/npm:node-10.10.0'
  args: ['version']


images:
- 'gcr.io/$PROJECT_ID/npm:latest'
- 'gcr.io/$PROJECT_ID/npm:current'
- 'gcr.io/$PROJECT_ID/npm:node-10.10.0'